CREATE TABLE IF NOT EXISTS simulation_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bit_length INT NOT NULL,
  eve_present BOOLEAN NOT NULL,
  qber FLOAT NOT NULL,
  is_safe BOOLEAN NOT NULL,
  aes_key VARCHAR,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE simulation_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous select" ON simulation_sessions;
DROP POLICY IF EXISTS "Allow anonymous insert" ON simulation_sessions;
DROP POLICY IF EXISTS "Allow anonymous delete" ON simulation_sessions;

CREATE POLICY "Allow anonymous select" ON simulation_sessions FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anonymous insert" ON simulation_sessions FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anonymous delete" ON simulation_sessions FOR DELETE TO anon USING (true);
